### ISSUE TITLE
Deprecation warning with stylelint-scss 5.3.0 (5.2.1+?)

### ISSUE THREAD

**Issue by tagliala** [stylelint-scss/stylelint-config-recommended-scss#251]
Hello,

I'm getting a deprecation warning after upgrading ~stylelint-scss to 5.3.0~ something and *I think* (apologies if this is not the case, I'm not a javascript developer) it may be triggered by this library, which I'm using as a dependency of `stylelint-config-twbs-bootstrap` and `stylelint-config-standard-scss`

https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/b976432477b8cf955d728c2236b05bac88abe943/index.js#L23

```
Deprecation warnings:
 - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
 - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
```

Ref: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/6688272782/job/18170091224#step:6:13

Update: I'm seeing this deprecation message also on 5.2.1.

```
Deprecation warnings:
 - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
 - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
```

**Comment by Alkarex** [comment]
@tagliala Tests welcome https://github.com/stylelint-scss/stylelint-config-recommended-scss/pull/252
