### ISSUE TITLE
Support stylelint16 

### ISSUE THREAD

**Issue by newives** [stylelint-scss/stylelint-config-recommended-scss#264]
Support stylelint16 https://stylelint.io/migration-guide/to-16/

**Comment by kolorfilm** [comment]
Jup same problem. I get:

_Error: Could not find "stylelint-scss". Do you need the "configBasedir" or "--config-basedir" option?_

**Comment by FloEdelmann** [comment]
Blocked by

* https://github.com/stylelint-scss/stylelint-scss/issues/894

**Comment by kristerkari** [comment]
I'll try my best to get a new version with `stylelint-scss` v6 support out today.

**Comment by kristerkari** [comment]
New release out: https://github.com/stylelint-scss/stylelint-config-recommended-scss/releases/tag/v14.0.0
