### ISSUE TITLE
Disable function-no-unknown rule

### ISSUE THREAD

**Issue by rchl** [stylelint-scss/stylelint-config-recommended-scss#92]
The `function-no-unknown` rule will complain about scss functions like `math.div` and other.

Would it make sense to explicitly disable it in this config to cater for cases when extending a config that enables it?

Also see https://github.com/ota-meshi/stylelint-config-recommended-vue/issues/26

**Comment by kristerkari** [comment]
Makes sense for SCSS indeed.

**Comment by ybiquitous** [comment]
Hi there,

[`stylelint-scss@4.2.0`](https://github.com/stylelint-scss/stylelint-scss/releases/tag/v4.2.0) now has the [`scss/function-no-unknown`](https://github.com/stylelint-scss/stylelint-scss/blob/v4.2.0/src/rules/function-no-unknown/README.md) rule, so enabling the new rule seems to make sense:

```json
{
  "rules": {
    "function-no-unknown": null,
    "scss/function-no-unknown": true
  }
}
```

**Comment by rchl** [comment]
It might seem like it does but it's one of those rules that will easily trigger in various projects and would need manual adjustments so IMO it's not something that should be enabled by default.

For example it triggers on this line:
https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/6c2357ee14dd9dcf29c6a101919a261c6b61748d/__tests__/valid.scss#L119-L119
in this repo because the custom function is not whitelisted.

**Comment by ybiquitous** [comment]
Surely. @rchl's idea seems to make sense to me. 👍🏼

**Comment by kristerkari** [comment]
Yeah, let's not enable the SCSS version as it would just trigger errors for any custom functions that the users are using.

**Comment by amk221** [comment]
I think this doesn't work for negative values

```css
margin-left: -#{$value}  /*  Unexpected unknown function "-"  scss/function-no-unknown */
```

**Comment by kristerkari** [comment]
@amk221 could you please open a new Github issue about the bug? :)

**Comment by amk221** [comment]
Sure, is there a way I can write a failing test? I'm not familiar with the project and I couldn't find any

**Comment by kristerkari** [comment]
@amk221 the rule and the tests can be found from the `stylelint-scss` repo: https://github.com/stylelint-scss/stylelint-scss/tree/master/src/rules/function-no-unknown
